# Generated by Django 5.2.7 on 2025-11-13 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='job',
        ),
        migrations.RemoveField(
            model_name='application',
            name='user',
        ),
        migrations.DeleteModel(
            name='Job',
        ),
        migrations.DeleteModel(
            name='Application',
        ),
    ]
