# Generated by Django 5.2.7 on 2025-11-14 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='contactno',
        ),
    ]
